import 'package:flutter/material.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

import 'custom_color.dart';
class CustomTextStyle{
  static TextStyle textSignUpWhite=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color: Colors.white);
  static TextStyle textSubmit=TextStyle(fontSize: 11.px,fontWeight: FontWeight.w500, color: Colors.white);
  static TextStyle textTaskChat=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor13);
  static TextStyle textTaskChat1=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor13);
  static TextStyle textSignUpWhite1=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color: Colors.white);
  static TextStyle textLoginOrange=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor);
  static TextStyle textLoginOrange1=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.orangeColor1);
  static TextStyle textLoginBlack=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textExploreBlack=TextStyle(fontSize: 18.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor);
  static TextStyle textStartBlack=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textWelcomeBlack=TextStyle(fontSize: 18.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textAccountBlack=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor);
  static TextStyle textCarpenter=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle chatSupport=TextStyle(fontSize: 20.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle textAccountBlack1=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textBank=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w700, color:CustomColor.blackColor);
  static TextStyle textData=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textPostcode=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w800, color:CustomColor.blackColor);
  static TextStyle textReview=TextStyle(fontSize: 22.px,fontWeight: FontWeight.w700, color:CustomColor.blackColor);
  static TextStyle textReview1=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w400, color:CustomColor.greyColorReview);
  static TextStyle textCancel=TextStyle(fontSize: 11.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor2);
  static TextStyle textEmailBlack=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textForgotOrange=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.orangeColor1);
  static TextStyle textForgotOrange1=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.orangeColor1);
  static TextStyle textDetails=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.orangeColor1);
  static TextStyle textBlackColor2=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor2);
  static TextStyle textWithBlack=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor);
  static TextStyle textOpiBlack=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor1);
  static TextStyle textSignUpOrange=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle textResetOrange=TextStyle(fontSize: 22.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle textResetOrange1=TextStyle(fontSize: 20.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle textExampleBlack=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w900, color:CustomColor.blackColor3);
  static TextStyle textOtpBlack=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor4);
  static TextStyle textSearchOrange1=TextStyle(fontSize: 20.px,fontWeight: FontWeight.w700, color:CustomColor.orangeColor1);
  static TextStyle textLeft=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textPerfectBlack6=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor6);
  static TextStyle textSeeAllOrange1=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w500, color:CustomColor.orangeColor1);
  static TextStyle textAudioBlack=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w800, color:CustomColor.blackColor);
  static TextStyle textConstructionBlack5=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor5);
  static TextStyle textNameBlack7=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor7);
  static TextStyle textNameBlack8=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor8);
  static TextStyle textNameBlack6=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor6);
  static TextStyle textNameBlackNew=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor6);
  static TextStyle textNameBlack9=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor9);
  static TextStyle textNameBlack2=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor2);
  static TextStyle textNameBlack1=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor1);
  static TextStyle textAddOrange1=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w700, color:CustomColor.orangeColor1);
  static TextStyle textAddBlack1=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor2);
  static TextStyle textAddBlack6=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor6);
  static TextStyle textBlack1=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor1);
  static TextStyle textTask=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor6);
  static TextStyle textWhite1=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:Colors.white);
  static TextStyle textBlackColor5=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.orangeColor1);
  static TextStyle textBlackColor6=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w600, color:CustomColor.blackColor6);
  static TextStyle textBlackColor=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textCancel1=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:Colors.white);
  static TextStyle textBlack=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor1);
  static TextStyle textBlack6=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor6);
  static TextStyle textDesc=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor6);
  static TextStyle textB=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w700, color:CustomColor.blackColor);
  static TextStyle textBlue=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blueColor);
  static TextStyle greyColorSite=TextStyle(fontSize: 12.5.px,fontWeight: FontWeight.w400, color:CustomColor.greyColorSite);
  static TextStyle textProfile=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor11);
  static TextStyle textName=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textName2=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor2);
  static TextStyle textName3=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor);
  static TextStyle textTime=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor1);
  static TextStyle text5=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w700, color:CustomColor.greyColor6);
  static TextStyle textName1=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor8);
  static TextStyle textNameBalance=TextStyle(fontSize: 20.px,fontWeight: FontWeight.w400, color:Colors.white);
  static TextStyle textDollarBalance=TextStyle(fontSize: 24.px,fontWeight: FontWeight.w500, color:Colors.white);
  static TextStyle textWhite=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w500, color:Colors.white);
  static TextStyle textRed=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.redColor3);
  static TextStyle textReviewCancel=TextStyle(fontSize: 11.px,fontWeight: FontWeight.w500, color:CustomColor.blackColor2);
  static TextStyle textGreen=TextStyle(fontSize: 14.px,fontWeight: FontWeight.w400, color:CustomColor.greenColor);
  static TextStyle textLight=TextStyle(fontSize: 11.px,fontWeight: FontWeight.w400, color:CustomColor.greyColor8);
  static TextStyle textLight1=TextStyle(fontSize: 10.px,fontWeight: FontWeight.w400, color:CustomColor.blackColor5);
  static TextStyle blackColorN=TextStyle(fontSize: 16.px,fontWeight: FontWeight.w500, color:CustomColor.blackColorN);
  static TextStyle greyColor10=TextStyle(fontSize: 12.px,fontWeight: FontWeight.w400, color:CustomColor.greyColor10);
  static TextStyle upgrade=TextStyle(fontSize: 24.px,fontWeight: FontWeight.w700, color:CustomColor.blackColor);





}
